server:
  port: 10000

spring:
  application:
    name: recipe-manager

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gj_food?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: guoyoukun

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.recipe.entity
  configuration:
    map-underscore-to-camel-case: true  # 数据库下划线字段自动映射为驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL

logging:
  level:
    com.example.recipe: info

file:
  path: 'D:/img'
  external-url: http://127.0.0.1:10000
